paranal:
  api_url: "http://archive.eso.org/wdb/wdb/asm/meteo_paranal/query"
  payload: None
  location_idx: 0
lasilla:
  api_url: "http://archive.eso.org/wdb/wdb/asm/meteo_lasilla/query"
  payload: None
  location_idx: 1
apex:
  api_url: "http://archive.eso.org/wdb/wdb/asm/meteo_apex/query"
  payload: None
  location_idx: 2
start_year : 2007
end_year : 2024
db_name : Meteo_test
collection_name : Meteo_test