host_port: mongodb://localhost:27017/
db_name: Meteo_test
collection_pure_samples: Meteo_test
collection_test: test
collection_train: train
remove: 0.3
stride: 5
context_len: 10
time_norm: 259200
len_test: 162
len_train: 378