numeric_cols_paranal = [
    'Air Pressure at ground [hPa]',
    'Air Pressure Normalised [hPa]',
    'Air Temperature at 30m [C]',
    'Air Temperature at 2m [C]',
    'Air Temperature at ground [C]',
    'Air Temperature below VLT [C]',
    'Dew Temperature at 30m [C]',
    'Dew Temperature at 2m [C]',
    'Dew Temperature below VLT [C]',
    'Rain intensity below VLT [%]',
    'Relative Humidity at 30m [%]',
    'Relative Humidity at 2m [%]',
    'Relative Humidity below VLT [%]',
    'Wind Direction at 30m (0/360) [deg]',
    'Wind Direction at 30m (180/-180) [deg]',
    'Wind Direction at 10m (0/360) [deg]',
    'Wind Direction at 10m (180/-180) [deg]',
    'Wind Speed at 30m [m/s]',
    'Wind Speed at 10m [m/s]',
    'Wind Speed U at 20m [m/s]',
    'Wind Speed V at 20m [m/s]',
    'Wind Speed W at 20m [m/s]',
    'Air Pressure instantanous [hPa]',
    'Air Temperature instantanous at 30m [C]',
    'Air Temperature instantanous at 2m [C]',
    'Air Temperature instantanous at ground [C]',
    'Air Temperature instantaneous below VLT [C]',
    'Dew Temperature istantaneous at 30m [C]',
    'Dew Temperature instantanous at 2m [C]',
    'Dew Temperature instantanous below VLT [C]',
    'Humidity instantanous at 30m [%]',
    'Humidity instantanous at 2m [%]',
    'Humidity instantanous below VLT [%]',
    'Rain intensity instantanous [%]',
    'Wind Direction instantanous at 30m [deg]',
    'Wind Direction instantanous at 10m [deg]',
    'Wind Speed instantanous at 30m [m/s]',
    'Wind Speed instantanous at 10m [m/s]',
    'Wind Speed U instantanous at 20m [m/s]',
    'Wind Speed V instantanous at 20m [m/s]',
    'Wind Speed W instantanous at 20m [m/s]',
    'Particle (Large) at 20m [1/m^3]',
    'Particle (Large) at 10m [1/m^3]',
    'Particle (Small) at 20m [1/m^3]',
    'Particle (Small) at 10m [1/m^3]',
    'Particle (Large) Instantanous at 20m [1/m^3]',
    'Particle (Large) instantanous at 10m [1/m^3]',
    'Particle (Small) instantanous at 20m [1/m^3]',
    'Particle (Small) instantanous at 10m [1/m^3]',
 ]


numeric_cols_using = [
 'Air Pressure at ground [hPa]',
 'Air Pressure Normalised [hPa]',
 'Air Temperature at 30m [C]',
 'Air Temperature at 2m [C]',
 'Air Temperature at ground [C]',
 'Air Temperature below VLT [C]',
 'Dew Temperature at 30m [C]',
 'Dew Temperature at 2m [C]',
 'Dew Temperature below VLT [C]',
 'Rain intensity below VLT [%]',
 'Relative Humidity at 30m [%]',
 'Relative Humidity at 2m [%]',
 'Relative Humidity below VLT [%]',
 'Wind Direction at 30m (0/360) [deg]',
 'Wind Direction at 30m (180/-180) [deg]',
 'Wind Direction at 10m (0/360) [deg]',
 'Wind Direction at 10m (180/-180) [deg]',
 'Wind Speed at 30m [m/s]',
 'Wind Speed at 10m [m/s]',
 'Wind Speed U at 20m [m/s]',
 'Wind Speed V at 20m [m/s]',
 'Wind Speed W at 20m [m/s]',
 'Air Pressure instantanous [hPa]',
 'Air Temperature instantanous at 30m [C]',
 'Air Temperature instantanous at 2m [C]',
 'Air Temperature instantanous at ground [C]',
 'Air Temperature instantaneous below VLT [C]',
 'Dew Temperature istantaneous at 30m [C]',
 'Dew Temperature instantanous at 2m [C]',
 'Dew Temperature instantanous below VLT [C]',
 'Humidity instantanous at 30m [%]',
 'Humidity instantanous at 2m [%]',
 'Humidity instantanous below VLT [%]',
 'Rain intensity instantanous [%]',
 'Wind Direction instantanous at 30m [deg]',
 'Wind Direction instantanous at 10m [deg]',
 'Wind Speed instantanous at 30m [m/s]',
 'Wind Speed instantanous at 10m [m/s]',
 'Wind Speed U instantanous at 20m [m/s]',
 'Wind Speed V instantanous at 20m [m/s]',
 'Wind Speed W instantanous at 20m [m/s]'
]

features_30m =[
 'Air Temperature at 30m [C]',
 'Dew Temperature at 30m [C]',
 'Relative Humidity at 30m [%]',
 'Wind Direction at 30m (0/360) [deg]',
 'Wind Direction at 30m (180/-180) [deg]',
 'Wind Speed at 30m [m/s]',
 'Air Temperature instantanous at 30m [C]',
 'Dew Temperature istantaneous at 30m [C]',
 'Humidity instantanous at 30m [%]',
 'Wind Direction instantanous at 30m [deg]',
 'Wind Speed instantanous at 30m [m/s]',
]

features_ground = [
 'Air Temperature at ground [C]',
 'Air Temperature instantanous at ground [C]',
]

features_2m = [
 'Air Temperature at 2m [C]',
 'Dew Temperature at 2m [C]',
 'Relative Humidity at 2m [%]',
 'Air Temperature instantanous at 2m [C]',
 'Dew Temperature instantanous at 2m [C]',
 'Humidity instantanous at 2m [%]',
]

features_vlt = [
 'Air Temperature below VLT [C]',
 'Dew Temperature below VLT [C]',
 'Rain intensity below VLT [%]',
 'Relative Humidity below VLT [%]',
 'Air Temperature instantaneous below VLT [C]',
 'Dew Temperature instantanous below VLT [C]',
 'Humidity instantanous below VLT [%]',
]

air_temp = [
 'Air Temperature instantanous at 30m [C]',
 'Air Temperature instantanous at ground [C]',
 'Air Temperature instantaneous below VLT [C]',
]